PROJECT_FOLDER_PATH = 'D:\Work\Personal\Projects\MF Returns Project\\'
CODE_SOURCES_FOLDER_PATH = PROJECT_FOLDER_PATH + 'Code\\'
STORAGE_FOLDER_PATH = PROJECT_FOLDER_PATH + 'Storage\\'
PROCESSED_DATA_FOLDER_PATH = STORAGE_FOLDER_PATH + 'Data Files\\'
PLOTS_FOLDER_PATH = STORAGE_FOLDER_PATH + 'Plots\\'
ANALYSED_DATA_FOLDER_PATH = STORAGE_FOLDER_PATH + 'Analysed Data\\'
SCHEMES_LIST_FILE_PREFIX = 'All Schemes List'
SCHEMES_LIST_FILE_PATH = PROCESSED_DATA_FOLDER_PATH + SCHEMES_LIST_FILE_PREFIX
AMFI_HTML_DATA_FOLDER_PATH = STORAGE_FOLDER_PATH + 'AMFI Data\\'
AMFI_HTML_DATA_FILE_PREFIX = 'AMFI_NAV_DATA'
AMFI_HTML_DATA_FILE_PATH = AMFI_HTML_DATA_FOLDER_PATH + AMFI_HTML_DATA_FILE_PREFIX
NAV_DATA_STATS_FILE_NAME = 'NAV Data Stats'
NAV_DATA_STATS_FILE_PATH = PROCESSED_DATA_FOLDER_PATH + NAV_DATA_STATS_FILE_NAME

CODE_FOLDERS_RELATIVE_PATH = ['MF Data Collector', 'MF Data Plotter', 'MF Data Processor', 'MF Data Service',
                              'MF Utils', 'Models']

